global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'celery_exporter'
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000'] # use api:8000 if the API runs in Docker.
